# Database
db.driver: oracle.jdbc.OracleDriver
db.url: jdbc:oracle:thin:@tcs-poc-customer-db-ca-i1.clsbnpfgdza7.ca-central-1.rds.amazonaws.com:1521:ORCL
db.username: tcsmspocdbadmin
db.password: microservices787

# Hibernate
hibernate.dialect: org.hibernate.dialect.Oracle10gDialect
hibernate.show_sql: true
hibernate.hbm2ddl.auto: update
hibernate.use_sql_comments: true
entitymanager.packagesToScan: com.product.entity

#Application
application.version: 1.0
spring.application.name: productservice

#logging
logging.config: classpath:log4j2.xml

#Eureka
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://tcs-poc-ms-eurekaserver.com/eureka
    
      
 #Ribbon
TCS-POC-MS-IDGENERATOR:
  ribbon:
    eureka:
      enabled: true
    
    ServerListRefreshInterval: 15000
